- name: NodeJS ve NPM kurulumu ve calistirilmasi
  hosts: droplets
  become: yes
  vars_files:
    - /workspaces/ansible_lecture/playbooks2/vars.yaml

  tasks:
    - name: apt update
      apt:
        update_cache: yes
        cache_valid_time: "{{cache_valid_time}}"
        force_apt_get: yes
      register: apt_result
    
    - name: apt update result
      debug: 
        var: apt_result

    - name: Install Node.js npm
      apt:
        pkg:
          - nodejs
          - npm
        state: present
      register: npm_install

    - name:
      debug:
        var: npm_install 

    - name: Create btw user
      user: 
        name: btw
        state: present
        create_home: yes

    - name: Nodejs uygulamasini unzip sunucuya kopyala
      unarchive:
         src: /workspaces/ansible_lecture/node-project-master.tar.gz
         dest: /home/btw/   
         remote_src: no
         owner: btw
         group: btw

    - name:
      npm:
        path: /home/btw/node-project-master/app/
      become_user: btw   

    - name: Start NodeJS
      command: npm start 
      args:
        chdir: /home/btw/node-project-master/app/
      async: 1000
      poll: 0        
      register: nodejs_start_status
      become_user: btw

    - name: 
      debug:
        var: nodejs_start_status  

    - name: Uygulama calisiyor mu
      shell: ps aux | grep node
      register: shell_result

    - name: 
      debug:
        var: shell_result.stdout_lines 
