- name: Ngnix kurulumu ve calistirilmasi
  hosts: droplets, aws
  become: yes

  tasks:
    - name: Install Ngnix
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"  

    - name: Install Ngnix
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"  
      register: yum_result
    
    - name: debug yum
      debug:
        var: yum_result

    - name: Start Ngnix
      service:
        name: nginx    
        state: started
        enabled: yes